// Post successfull login
# @name login
POST http://localhost:3000/auth/login HTTP/1.1
content-type: application/json

{
    "username": "testUser5",
    "password": "test123"
}

###
@authToken = {{login.response.body.access_token}}

// Get users
GET http://localhost:3000/users HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}

###

// POST users
POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "username": "testUser5",
    "email": "baptiste.franel5@gmail.com",
    "password": "test123"
}

###
// Get one user from id
@authToken = {{login.response.body.access_token}}
GET http://localhost:3000/users/1 HTTP/1.1
Authorization: Bearer {{authToken}}

###

// Post failed login
POST http://localhost:3000/auth/login HTTP/1.1
content-type: application/json

{
    "username": "testUser",
    "password": "failedPassword"
}

###
// Unauthorized route
GET http://localhost:3000/auth/profile HTTP/1.1


###
// Authorized route
@authToken = {{login.response.body.access_token}}
GET http://localhost:3000/auth/profile HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}


###
// Search by name or email
@authToken = {{login.response.body.access_token}}
GET http://localhost:3000/users/search?searchreq=test HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}


###